name: waterways
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  currency_symbols: ^0.0.1+2

  step_progress_indicator: ^1.0.2

  image_picker: ^1.0.5
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.6
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/NavBar-Icons/
    - assets/Login/
    - assets/Order/
    - assets/Main/
